// Generated by CoffeeScript 1.9.3
(function() {
  var calc, config, exp, fs, p, parse, print_tokens, tokenize, tokens;

  fs = require('fs');

  tokenize = require('./tokenize.js');

  print_tokens = require('./print-tokens.js');

  parse = require('./parse.js');

  calc = require('./calc.js');

  config = {
    tokens: ['./std-tokens.yml']
  };

  exp = fs.readFileSync(process.argv[2]).toString();

  tokens = tokenize(exp, config);

  console.log(print_tokens(tokens));

  p = parse(tokens);

  calc(p) + '';

}).call(this);
