// Generated by CoffeeScript 1.9.3
(function() {
  var color, colors, print_tokens, spaces;

  color = require('./color.js');

  colors = {
    'number': 'blue',
    'operator': 'cyan',
    'string': 'yellow',
    'annotation': 'red',
    'open_parinthesis': 'white',
    'close_parinthesis': 'white',
    'function_define': 'green',
    'default': 'white',
    'keyword': 'magenta'
  };

  spaces = {
    'number': [true, true],
    'operator': [true, true],
    'open_parinthesis': [true, false],
    'close_parinthesis': [false, true],
    'variable': [true, true],
    'function_call': [true, false],
    'comma': [false, true],
    'line_end': [false, true]
  };

  print_tokens = function(tokens) {
    var c, i, j, next_space, ref, res, space, this_space, v;
    res = '';
    for (i = j = 0, ref = tokens.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      c = colors.hasOwnProperty(tokens[i].type) ? colors[tokens[i].type] : colors['default'];
      v = color(tokens[i].value, c);
      next_space = i < tokens.length - 1 && spaces.hasOwnProperty(tokens[i + 1].type) ? spaces[tokens[i + 1].type][0] : true;
      this_space = spaces.hasOwnProperty(tokens[i].type) ? spaces[tokens[i].type][1] : true;
      space = this_space && next_space ? ' ' : '';
      res += v + space;
    }
    return res.replace(/\ $/, '');
  };

  module.exports = print_tokens;

}).call(this);
