// Generated by CoffeeScript 1.9.3
(function() {
  var Decimal;

  Decimal = require('./decimal.js');

  module.exports = {
    name: 'stdlib',
    description: 'The built-in library',
    variables: {
      PI: new Decimal('3.1415926535897932384626433832795028841971693993751'),
      E: new Decimal('2.7182818284590452353602874713526624977572470937000')
    },
    functions: {
      log: function(p) {
        return p[0].log();
      },
      sin: function(p) {
        return p[0].sin();
      },
      cos: function(p) {
        return p[0].cos();
      },
      tan: function(p) {
        return p[0].tan();
      },
      ln: function(p) {
        return p[0].ln();
      },
      asin: function(p) {
        return p[0].asin();
      },
      acos: function(p) {
        return p[0].acos();
      },
      atan: function(p) {
        return p[0].atan();
      },
      sqrt: function(p) {
        return p[0].sqrt();
      },
      cbrt: function(p) {
        return p[0].cbrt();
      },
      round: function(p) {
        return p[0].round();
      },
      floor: function(p) {
        return p[0].floor();
      },
      ceil: function(p) {
        return p[0].ceil();
      },
      factorial: function(p) {
        var i, n, res;
        if (p[0].lessThan(1000000)) {
          n = p[0].toString();
          res = new Decimal(1);
          i = 1;
          while (i <= n) {
            res = res.times(i);
            i += 1;
          }
          return res;
        } else {
          res = new Decimal(1);
          i = new Decimal(1);
          while (i.lessThanOrEqualTo(p[0])) {
            res = res.times(i);
            i = i.add(1);
          }
          return res;
        }
      },
      random: function(p) {
        var sd;
        sd = p[0] ? Number(p[0].toString()) : 10;
        return Decimal.random(sd);
      }
    }
  };

}).call(this);
